name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: runner.os != 'Windows'
        shell: bash
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: yarn install

      - name: Install audio utilities on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Install pulseaudio-utils (pactl) and alsa-utils (amixer). Attempt pipewire-bin (pw-cli) optionally.
          # Install each package separately so one missing package doesn't fail the whole command.
          sudo apt-get install -y pulseaudio-utils || true
          sudo apt-get install -y alsa-utils || true
          sudo apt-get install -y pipewire-bin || true

      - name: Build
        run: yarn build

      - name: Run unit tests
        run: yarn unit

      - name: Upload vitest coverage (if available)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: ./coverage

  integration:
    name: Integration tests (linux)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install audio utilities
        run: |
          sudo apt-get update
          # Install each package separately so one missing package doesn't fail the whole command.
          sudo apt-get install -y pulseaudio-utils || true
          sudo apt-get install -y alsa-utils || true
          sudo apt-get install -y pipewire-bin || true

      - name: Install dependencies
        shell: bash
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Build
        run: yarn build

      - name: "Debug: list audio binaries"
        run: |
          echo "Which pactl:"
          command -v pactl || true
          echo "pactl --version:"
          pactl --version || true
          echo "Which amixer:"
          command -v amixer || true
          echo "amixer --version:"
          amixer --version || true
          echo "Which pw-cli:"
          command -v pw-cli || true
          echo "pw-cli --version:"
          pw-cli --version || true
        shell: bash

      - name: Run linux integration test
        run: npx vitest --run test/linux.integration.spec.ts

