name: CI, Prebuilds & Release

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  test:
    name: Run tests on PRs
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn unit

  prebuild:
    name: Build prebuilds (release)
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'release'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Force rebuild native addon
        run: yarn rebuild:force

      - name: Prepare artifact directory
        run: |
          mkdir -p artifacts
          # Copy any built native modules into artifacts. Adjust path if your native addon outputs elsewhere.
          if [ -d build/Release ]; then cp -v build/Release/*.node artifacts/ || true; fi
        shell: bash

      - name: Upload prebuild artifact (per-job)
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-${{ matrix.os }}-node${{ matrix.node }}
          path: artifacts/

  release_upload:
    name: Package & upload prebuilds to GitHub Release
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: prebuild
    steps:
      - name: Download all prebuild artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded

      - name: List downloaded content
        run: ls -R downloaded

      - name: Package artifacts
        run: |
          mkdir -p packaged
          for d in downloaded/*; do
            # each $d is a folder named like prebuild-... containing .node files
            name=$(basename "$d")
            tar -C "$d" -czf "packaged/${name}.tar.gz" . || (zip -r "packaged/${name}.zip" . && true)
          done

      - name: Upload packaged prebuilds to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: packaged/
          asset_name: packaged
          asset_content_type: application/gzip

  publish-npm:
    name: Publish to npm (on release)
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: release_upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node for publish
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install & build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
